/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solitudeworks_jni_simple_sample_hello_HelloJNI */

#ifndef _Included_solitudeworks_jni_simple_sample_hello_HelloJNI
#define _Included_solitudeworks_jni_simple_sample_hello_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solitudeworks_jni_simple_sample_hello_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_solitudeworks_jni_simple_sample_hello_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
